### ISSUE TITLE
[FEATURE] Responsive Frontend

### ISSUE THREAD

**Issue by DebadityaPal** [DebadityaPal/PlagiarismChecker#2]
Currently, the website is not responsive, ideally, the website should be accessible from both Desktop and Mobile users. 
Hence, we need it to be responsive.
The contributor can fully decide how they want the frontend to behave as long as the functionality is not lost.

**Comment by gurpreet-legend** [comment]
I want to work on it

**Comment by DebadityaPal** [comment]
Sure @gurpreet-legend, contact me if you need any help!

**Comment by DebadityaPal** [comment]
I would suggest, you hold off the work till tomorrow, A new PR is being merged that will change the frontend. I don't want you to do the same work twice.

**Comment by gurpreet-legend** [comment]
> I would suggest, you hold off the work till tomorrow, A new PR is being merged that will change the frontend. I don't want you to do the same work twice.

Sure sir, do let me know when can I start :)

**Comment by DebadityaPal** [comment]
Hi @gurpreet-legend , the new PR has been merged, you can get started.

**Comment by DebadityaPal** [comment]
I would recommend you do a `git pull` before getting started to have the latest version of the code in your local.

**Comment by gurpreet-legend** [comment]
Sir, I have forked this Repo and have set up the server requirements on my forked Repo, should I make a Pull Request to update myself?

**Comment by DebadityaPal** [comment]
Add this repo to your local as a remote, then do `git pull <remote-name> main`
Follow these steps:
1. `git remote add upstream https://github.com/DebadityaPal/PlagiarismChecker`
2. `git pull upstream main`
3. `git push origin main`

This would update both your local and your fork.

**Comment by gurpreet-legend** [comment]
Your suggested changes have been done, you can review now @Debaditya-Pal

**Comment by DebadityaPal** [comment]
Yep, LGTM
