### ISSUE TITLE
[FEATURE] Beautification of frontend

### ISSUE THREAD

**Issue by DebadityaPal** [DebadityaPal/PlagiarismChecker#5]
Currently, the product works with a makeshift frontend that serves the basic purpose. However, we would appreciate a better frontend, so if anyone can help us out with that, we will be very grateful.
The contributor can change anything as long as the functionality of the product remains unchanged. 
Color schemes, Logos, everything can be changed.
So if someone wants to try out exploring UI/UX, this would be the perfect issue.

**Comment by kailash360** [comment]
I want to work on this issue

**Comment by DebadityaPal** [comment]
Sure! Please do ping me or @hs2361 if you need some help. 😄

**Comment by kailash360** [comment]
In the backend, the settings.py seems to be missing and it is not possible to run the app. Can you please share the necessary settings and configurations to run it?

**Comment by DebadityaPal** [comment]
I have added the required file. You should be able to run it now.

**Comment by kailash360** [comment]
Sir, while making a request, the backend gives the error mentioned below. Do I need to change anything in dependencies, or is it anything else?
![image](https://user-images.githubusercontent.com/75155230/135713819-8430203a-6782-4008-8c97-e7415c00347b.png)

**Comment by DebadityaPal** [comment]
What is the version of the `google` package that you are using? It should be `3.0.0`

**Comment by kailash360** [comment]
It worked now

**Comment by kailash360** [comment]
Sir, I have made the following modifications. Are there any changes to be made?
![image](https://user-images.githubusercontent.com/75155230/135725496-b9d330df-dfeb-4681-b175-2bd78e52ef7e.png)
![image](https://user-images.githubusercontent.com/75155230/135725509-88a40323-4312-4e45-8b63-cdb7cd161924.png)
![image](https://user-images.githubusercontent.com/75155230/135725522-1fc0dbd3-878a-4324-9263-95e19bcbbaf4.png)

**Comment by DebadityaPal** [comment]
This honestly looks wonderful! Great Work!

**Comment by DebadityaPal** [comment]
Create a pull request linking this issue, I'll be more than happy to merge it.

**Comment by kailash360** [comment]
I have created PR #8 for this issue
