### ISSUE TITLE
[FEATURE] Dependency management

### ISSUE THREAD

**Issue by DebadityaPal** [DebadityaPal/PlagiarismChecker#7]
Since the project wasn't started with a proper dependency management tool, the packages are all over the place. The [requirements.txt](https://github.com/DebadityaPal/PlagiarismChecker/blob/main/requirements.txt) file needs to be cleaned up. If the contributor can install  a proper dependency manager in place, it'll be very usefull.

**Comment by Anik-Bardhan** [comment]
@Debaditya-Pal can I be assigned to this? I can implement a dependency management tool like virtualenv for this project.

**Comment by DebadityaPal** [comment]
Hi @Anik-Bardhan , `virtualenv` is more of a dev environment. what I am looking for is something that can take a look at the installed packages and weed out the ones which aren't in use.
Maybe try `poetry`, though I don't know for sure if this functionality is available.
If you still wanna work on the issue, I'll be more than happy to assign it to you.

**Comment by Anik-Bardhan** [comment]
Basically a way to filter out libraries that were not used in the project. I want to work on it.

**Comment by DebadityaPal** [comment]
Sure! Feel free to reach out to me if you need any help.

**Comment by gaurav879** [comment]
Sir @DebadityaPal in this issue I just have to clean the requirements.txt file and remove the unnecessary modules, right ?

**Comment by DebadityaPal** [comment]
Yes @gaurav879, additionally you could also install a dependency manager to take care of this automatically in future. But the primary objective is to clean up `requirements.txt`

**Comment by gaurav879** [comment]
@DebadityaPal Sir, I would like to work on this issue.

**Comment by gaurav879** [comment]
@DebadityaPal sir any updates ?

**Comment by DebadityaPal** [comment]
Sorry for the delay @gaurav879 , sure go for it!

**Comment by gaurav879** [comment]
@DebadityaPal  Sir I have opened PR #10  that resolves this issue.
